`default_nettype none

package vec_pkg;

  // Source operand form
  typedef enum logic [1:0] {
    VEC_SRC_VV,
    VEC_SRC_VX,
    VEC_SRC_VI,
    VEC_SRC_NONE
  } vec_src_e;

  // Operand width shape
  typedef enum logic [1:0] {
    VEC_EEW_SAME,
    VEC_EEW_WIDEN,
    VEC_EEW_WIDEN_W,
    VEC_EEW_NARROW
  } vec_eew_e;

  typedef enum logic [6:0] {
    VEC_ADD,
    VEC_SUB,
    VEC_RSUB,
    VEC_MINU,
    VEC_MIN,
    VEC_MAXU,
    VEC_MAX,
    VEC_AND,
    VEC_OR,
    VEC_XOR,
    VEC_RGATHER,
    VEC_RGATHEREI16,
    VEC_SLIDEUP,
    VEC_SLIDEDOWN,
    VEC_ADC,
    VEC_MADC,
    VEC_SBC,
    VEC_MSBC,
    VEC_MERGE,
    VEC_MSEQ,
    VEC_MSNE,
    VEC_MSLTU,
    VEC_MSLT,
    VEC_MSLEU,
    VEC_MSLE,
    VEC_MSGTU,
    VEC_MSGT,
    VEC_SADDU,
    VEC_SADD,
    VEC_SSUBU,
    VEC_SSUB,
    VEC_SLL,
    VEC_SMUL,
    VEC_MVNRR,
    VEC_SRL,
    VEC_SRA,
    VEC_SSRL,
    VEC_SSRA,
    VEC_NSRL,
    VEC_NSRA,
    VEC_NCLIPU,
    VEC_NCLIP,
    VEC_WREDSUMU,
    VEC_WREDSUM,
    VEC_REDSUM,
    VEC_REDAND,
    VEC_REDOR,
    VEC_REDXOR,
    VEC_REDMINU,
    VEC_REDMIN,
    VEC_REDMAXU,
    VEC_REDMAX,
    VEC_AADDU,
    VEC_AADD,
    VEC_ASUBU,
    VEC_ASUB,
    VEC_SLIDE1UP,
    VEC_SLIDE1DOWN,
    VEC_MV_X_S,
    VEC_CPOP,
    VEC_FIRST,
    VEC_MV_S_X,
    VEC_ZEXT2,
    VEC_ZEXT4,
    VEC_ZEXT8,
    VEC_SEXT2,
    VEC_SEXT4,
    VEC_SEXT8,
    VEC_MSBF,
    VEC_MSOF,
    VEC_MSIF,
    VEC_IOTA,
    VEC_ID,
    VEC_COMPRESS,
    VEC_MANDN,
    VEC_MAND,
    VEC_MOR,
    VEC_MXOR,
    VEC_MORN,
    VEC_MNAND,
    VEC_MNOR,
    VEC_MXNOR,
    VEC_DIVU,
    VEC_DIV,
    VEC_REMU,
    VEC_REM,
    VEC_MULHU,
    VEC_MUL,
    VEC_MULHSU,
    VEC_MULH,
    VEC_MADD,
    VEC_NMSUB,
    VEC_MACC,
    VEC_NMSAC,
    VEC_WADDU,
    VEC_WADD,
    VEC_WSUBU,
    VEC_WSUB,
    VEC_WMULU,
    VEC_WMULSU,
    VEC_WMUL,
    VEC_WMACCU,
    VEC_WMACC,
    VEC_WMACCUS,
    VEC_WMACCSU,
    VEC_LOAD,
    VEC_STORE,
    VEC_ILLEGAL
  } vec_op_e;

endpackage

`default_nettype wire
